### ISSUE TITLE
Repair booking Widget tax class

### ISSUE THREAD

**Issue by simardm** [Repair-DeskPOS/RepairDesk-Bugs#112]
Hi, we would like to remove the tax displayed on the widget when selecting a repair, so our potential costumers wont assume that we will charge tax on top of the displayed price which already tax included. See screencap below, the highlighted price should have been 79.99$ instead of 91.97$
![prix eureka mobile reparation et deverrouillage d appareils mobiles au quebec](https://cloud.githubusercontent.com/assets/23082016/20323453/cce5db0c-ab4a-11e6-8f23-12ed2ad93d87.png)

**Comment by HafizAnas** [comment]
Hi @simardm 
we have updated repair booking widget and your reported issue has been fixed as well.
Please confirm at your end and do let us know if you have any question.

**Comment by simardm** [comment]
Same problem still...

![prix eureka mobile reparation et deverrouillage d appareils mobiles au quebec](https://cloud.githubusercontent.com/assets/23082016/20445351/c2ca3316-ada2-11e6-98cc-054b814112b4.png)
