### ISSUE TITLE
Sales Value Issue

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#89]
Dear @HafizAnas

One of our customer Andrew from "Kixup iPhone Repairs" reported the issue that sales value is different between the sales summary report and the reports dashboard.
I checked it from my side. Sales Value is different in dashboard, sales summary report and Reports Dashboard. Tax value is correct on all places. 
Can you please check why difference is coming up in "Sales" value and assign it to @muhammadfayyaz3 and get it fixed. I have attached screenshots for the reference. 
I will send you account details in personal message.

![dashboard value week](https://cloud.githubusercontent.com/assets/22955861/20047761/26a9e3fe-a4d9-11e6-937b-626e62d3dc1f.png)
![report dashboard](https://cloud.githubusercontent.com/assets/22955861/20047762/26b21c40-a4d9-11e6-9dd7-d182295758a5.png)

**Comment by HafizAnas** [comment]
Dear @muhammadfayyaz3 Muhammad Fayyaz

I have also confirmed this at my end. Both reports stats and dashboard has different values. Please fix  this issue asap.

**Comment by hafeezshahid** [comment]
@aishahanif Issues Fixed and Reviewed on Staging, Please make it live.

**Comment by afrahm** [comment]
Has this been applied into production environment yet? As the sales values are still different. The attached image is for Nov. 10
![screenshot 2016-11-11 09 48 31](https://cloud.githubusercontent.com/assets/1414304/20199104/0f53f7c6-a7f4-11e6-8a43-6705c54bcb1b.png)

**Comment by HafizAnas** [comment]
Hi @afrahm 
Sorry for this trouble again, your reported issue has been fixed and we will live it with in few hours.

**Comment by afrahm** [comment]
Has this been made live now? As I am still having the same issue??
<img width="1430" alt="screen shot 2016-11-12 at 11 50 21 am" src="https://cloud.githubusercontent.com/assets/1414304/20234837/858547c6-a8ce-11e6-8811-42e02970d4c1.png">

**Comment by Uzair-RepairDesk** [comment]
Hi Andrew @afrahm 
Our QA resource has checked your account in detail and he also checked invoices of 10 November.
Actually the system takes line total values from each invoice and sum up all the individual line total in "Location Sales by Item Type" report. If you give overall discount, it doesn't exclude it from Sales Value so total sales value may differ in case of "Location Sales by Item Type" report. You have given overall discount in invoice # 964 on 10 November so there is difference coming up in these 2 sales value (According to attached screenshot). However we have fixed the rounding issue in RepairDesk so Total Sales Value on Dashboard, Report Dashboard and Sales Summary report will be same now.
